---
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3314/demo_db
    username: user
    password: password

# restとSQLのログだけデバッグレベルで出力
logging:
  level:
    web: DEBUG
    api.management.task.infrastructure.mapper: DEBUG