openapi: 3.0.1
info:
  title: タスク管理API
  description: ユーザーのタスク管理関連のAPIを提供します
  version: v1
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: mock/v1/
    description: 動作チェック用コントローラ
paths:
  /mock/v1/hello:
    get:
      tags:
        - mock/v1/
      summary: 動作確認要エンドポイント
      operationId: get
      responses:
        "200":
          description: Hello world
          content:
            text/plain: {}
        "500":
          $ref: '#/components/responses/internalServerError'
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "403":
          $ref: '#/components/responses/forbidden'
components:
  schemas:
    ProblemResponse:
      type: object
      properties:
        title:
          type: string
          description: 問題の要素
          example: リソースが見つかりません
        status:
          type: integer
          description: HTTPレスポンスコード
          format: int32
          example: 404
        detail:
          type: string
          description: 問題の詳細
          example: 指定されたクイズが見つかりません
      description: RFC7807準拠のエラー詳細
  responses:
    badRequest:
      description: リクエストパラメータが不正
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemResponse'
          example: "{\"title\":\"リクエストされたパラメータは正しくありません\",\"status\":400,\"detail\"\
            :\"questionは必須項目です\"}"
    unauthorized:
      description: 認証情報がリクエストに付与されていない
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemResponse'
          example: "{\"title\":\"認証に失敗しました\",\"status\":401,\"detail\":\"認証情報が付与され\
            ていません\"}"
    forbidden:
      description: 許可されていないアクセス
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemResponse'
          example: "{\"title\":\"アクセスが拒否されました\",\"status\":403,\"detail\":\"アクセスする\
            権限がありません\"}"
    internalServerError:
      description: 処理が正常に終了しなかった
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemResponse'
          example: "{\"title\":\"リクエストされた操作を完了できませんでした\",\"status\":500,\"detail\"\
            :\"データベースでエラーが発生しました\"}"
