name: Gradle Test

on:
  push:
    # publishの方で gradle build　を動かしている関係でmaster/main以外にpushした場合に testを動かす
    branches:
      - '**'
      - '!master'
      - '!main'
  pull_request:
    # master/develop/main ブランチ向けのPRで gradle testを実行
    branches:
      - master
      - main
      - develop
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Change gradlew permissions
      run: chmod +x ./gradlew

    - name: gradle test
      run: ./gradlew test
